<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("blog");
?><p>
	 <?$APPLICATION->IncludeComponent(
	"bitrix:blog",
	"one_blog1",
	Array(
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_SHADOW" => "Y",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_PAGINATION" => "N",
		"AJAX_POST" => "Y",
		"ALLOW_POST_CODE" => "Y",
		"ALLOW_POST_MOVE" => "N",
		"BLOG_COUNT" => "20",
		"BLOG_COUNT_MAIN" => "6",
		"BLOG_PROPERTY" => "",
		"BLOG_PROPERTY_LIST" => "",
		"BLOG_URL" => "admin-blog-s1",
		"CACHE_TIME" => "36000000",
		"CACHE_TIME_LONG" => "60480000",
		"CACHE_TYPE" => "A",
		"COLOR_TYPE" => "Y",
		"COMMENTS_COUNT" => "25",
		"COMMENTS_LIST_VIEW" => "N",
		"COMMENT_ALLOW_IMAGE_UPLOAD" => "A",
		"COMMENT_ALLOW_VIDEO" => "N",
		"COMMENT_EDITOR_CODE_DEFAULT" => "N",
		"COMMENT_EDITOR_DEFAULT_HEIGHT" => "200",
		"COMMENT_EDITOR_RESIZABLE" => "Y",
		"COMMENT_PROPERTY" => "",
		"COMPONENT_TEMPLATE" => "one_blog",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"DO_NOT_SHOW_MENU" => "Y",
		"DO_NOT_SHOW_SIDEBAR" => "Y",
		"EDITOR_CODE_DEFAULT" => "N",
		"EDITOR_DEFAULT_HEIGHT" => "300",
		"EDITOR_RESIZABLE" => "Y",
		"GROUP_ID" => array(0=>"",1=>"",),
		"IMAGE_MAX_HEIGHT" => "600",
		"IMAGE_MAX_WIDTH" => "600",
		"MESSAGE_COUNT" => "10",
		"MESSAGE_COUNT_MAIN" => "6",
		"MESSAGE_LENGTH" => "100",
		"NAME_TEMPLATE" => "",
		"NAV_TEMPLATE" => "arrows",
		"NOT_USE_COMMENT_TITLE" => "Y",
		"NO_URL_IN_COMMENTS" => "",
		"NO_URL_IN_COMMENTS_AUTHORITY" => "",
		"PATH_TO_SMILE" => "/bitrix/images/blog/smile/",
		"PERIOD" => "",
		"PERIOD_DAYS" => "30",
		"PERIOD_NEW_TAGS" => "",
		"POST_PROPERTY" => "",
		"POST_PROPERTY_LIST" => "",
		"RATING_TYPE" => "",
		"SEF_FOLDER" => "/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("index_"=>"index.php","group"=>"group/#group_id#.php","blog"=>"","user"=>"user/#user_id#.php","user_friends"=>"friends/#user_id#.php","search"=>"search.php","user_settings"=>"#blog#/user_settings.php","user_settings_edit"=>"#blog#/user_settings_edit.php?id=#user_id#","group_edit"=>"#blog#/group_edit.php","blog_edit"=>"blog_edit/","category_edit"=>"#blog#/category_edit.php","post_edit"=>"edit/#post_id#/","draft"=>"draft/","moderation"=>"moderation/","trackback"=>POST_FORM_ACTION_URI."&blog=#blog#&id=#post_id#&page=trackback","post"=>"#post_id#/","post_rss"=>"rss/#post_id#","rss"=>"rss/","rss_all"=>"rss2/",),
		"SEO_USE" => "Y",
		"SEO_USER" => "N",
		"SET_NAV_CHAIN" => "N",
		"SET_TITLE" => "Y",
		"SHOW_LOGIN" => "Y",
		"SHOW_NAVIGATION" => "Y",
		"SHOW_RATING" => "",
		"SHOW_SPAM" => "N",
		"SMILES_COUNT" => "4",
		"THEME" => "blue",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USER_PROPERTY" => "",
		"USER_PROPERTY_NAME" => "",
		"USE_ASC_PAGING" => "N",
		"USE_GOOGLE_CODE" => "Y",
		"USE_SHARE" => "N",
		"VARIABLE_ALIASES" => array("user_settings_edit"=>array("user_id"=>"id",),"trackback"=>array("blog"=>"blog","post_id"=>"id",),),
		"WIDTH" => "100%"
	)
);?> 
</p>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>